"""add_usage_counters_table

Revision ID: 28a183216953
Revises: c912425aeba5
Create Date: 2026-08-28 03:13:04.740636
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '28a183216953'
down_revision: Union[str, None] = 'c912425aeba5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('ciphertext', sa.Text(), nullable=False),
    sa.Column('iv', sa.String(length=24), nullable=False),
    sa.Column('salt', sa.String(length=24), nullable=False),
    sa.Column('source_locale', sa.String(length=10), nullable=False),
    sa.Column('table_id', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('input_format', sa.String(length=10), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('translation_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_translation_history_source_locale'), ['source_locale'], unique=False)
        batch_op.create_index(batch_op.f('ix_translation_history_user_id'), ['user_id'], unique=False)

    op.create_table('usage_counters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('characters_processed', sa.BigInteger(), nullable=False),
    sa.Column('request_count', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_counters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_counters_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_counters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_counters_user_id'))

    op.drop_table('usage_counters')
    with op.batch_alter_table('translation_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_translation_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_translation_history_source_locale'))

    op.drop_table('translation_history')
    # ### end Alembic commands ###