"""add output_format to translation_profiles

Revision ID: 57505cae72c6
Revises: c80acaefa4f6
Create Date: 2026-08-31 20:58:29.188691
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '57505cae72c6'
down_revision: Union[str, None] = 'c80acaefa4f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translation_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('output_format', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translation_profiles', schema=None) as batch_op:
        batch_op.drop_column('output_format')

    # ### end Alembic commands ###