"""add_translation_profiles

Revision ID: a330ca0547d1
Revises: d4e91c2f7a30
Create Date: 2026-08-30 10:34:02.543038
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'a330ca0547d1'
down_revision: Union[str, None] = 'd4e91c2f7a30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('table_id', sa.String(length=50), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('layout', sa.String(length=50), nullable=True),
    sa.Column('grade', sa.String(length=20), server_default='grade2', nullable=False),
    sa.Column('contraction_categories', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('translation_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_translation_profiles_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translation_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_translation_profiles_user_id'))

    op.drop_table('translation_profiles')
    # ### end Alembic commands ###