"""add_rbac_roles_plans_entitlements

Revision ID: bcaa75c38a55
Revises: 28a183216953
Create Date: 2026-08-29 15:11:33.480676
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'bcaa75c38a55'
down_revision: Union[str, None] = '28a183216953'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entitlements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan_code', sa.String(length=50), nullable=False),
    sa.Column('feature_code', sa.String(length=50), nullable=False),
    sa.Column('limit_value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entitlements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entitlements_plan_code'), ['plan_code'], unique=False)

    op.create_table('plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan_code', sa.String(length=50), nullable=False),
    sa.Column('name_tr', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('description_tr', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('price_monthly', sa.Integer(), nullable=False),
    sa.Column('price_annual', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plans_plan_code'), ['plan_code'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), server_default='user', nullable=False))
        batch_op.add_column(sa.Column('plan_code', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('plan_code')
        batch_op.drop_column('role')

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plans_plan_code'))

    op.drop_table('plans')
    with op.batch_alter_table('entitlements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entitlements_plan_code'))

    op.drop_table('entitlements')
    # ### end Alembic commands ###