"""add_page_settings_to_profiles

Revision ID: c80acaefa4f6
Revises: a330ca0547d1
Create Date: 2026-08-30 14:58:40.416072
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'c80acaefa4f6'
down_revision: Union[str, None] = 'a330ca0547d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translation_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page_settings', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translation_profiles', schema=None) as batch_op:
        batch_op.drop_column('page_settings')

    # ### end Alembic commands ###