"""add translation_history table

Revision ID: c912425aeba5
Revises: 1a44b62bf810
Create Date: 2026-08-28 01:55:31.848840
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'c912425aeba5'
down_revision: Union[str, None] = '1a44b62bf810'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###